<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AccountPlaner_ADDNEW</name>
   <tag></tag>
   <elementGuidId>90c1406b-da03-4115-8378-204edfe82ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//accounts-planner[@class='ng-star-inserted']/div[2]/div[4]//kendo-tabstrip/div[1]/product-costing[@class='ng-star-inserted']/div/div[1]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//accounts-planner[@class='ng-star-inserted']/div[2]/div[4]//kendo-tabstrip/div[1]/product-costing[@class='ng-star-inserted']/div/div[1]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
