<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_save</name>
   <tag></tag>
   <elementGuidId>6d5d98a0-cb2e-4590-902b-5863d5478a39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//accounts-planner[@class='ng-star-inserted']/div[2]/div[1]/div/button[text()='Save']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//accounts-planner[@class='ng-star-inserted']/div[2]/div[1]/div/button[text()='Save']</value>
   </webElementProperties>
</WebElementEntity>
