<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_versions</name>
   <tag></tag>
   <elementGuidId>8714b36e-849c-4f18-b240-854a6b325776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//accounts-planner[@class='ng-star-inserted']/div[2]/div[1]//kendo-dropdownbutton/button[contains(.,'Versions')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//accounts-planner[@class='ng-star-inserted']/div[2]/div[1]//kendo-dropdownbutton/button[contains(.,'Versions')]</value>
   </webElementProperties>
</WebElementEntity>
