<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddb_category</name>
   <tag></tag>
   <elementGuidId>e11e9f0f-9f9f-4be3-b43d-b5f647dc6f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//compass-plan-selection-header-component/div[2]/div[2]/span[3]/kendo-dropdownlist/span[@role='listbox']/span[@class='k-select']</value>
   </webElementProperties>
</WebElementEntity>
