<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_hamburg</name>
   <tag></tag>
   <elementGuidId>e8babaf6-1f85-4fa9-8a89-907e8d3063b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='wrapper']/div[1]/div/div[1]//i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[1]/div/div[1]//i</value>
   </webElementProperties>
</WebElementEntity>
