<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Spinner</name>
   <tag></tag>
   <elementGuidId>ed042d5d-8b46-4554-9301-be98622cd749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//compass-plan-selection-header-component//div//*[@class='spinner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//compass-plan-selection-header-component//div//*[@class='spinner']</value>
   </webElementProperties>
</WebElementEntity>
